image: markhobson/maven-chrome:jdk-17

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


test:
  stage: test
  script:
    - mvn test -Dtest=testrunners.MyTestRunner  -DfailIfNoTests=false
    - cp -R htmlOutput/ target/
    - cp -R pdfOutput/ target/

  artifacts:
    paths:
      - target/*





